// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA253aK1P1rhW9DhryYexhzs-oBpRIPMMw',
    appId: '1:321135360177:web:cd19b7b5b9d00503064a90',
    messagingSenderId: '321135360177',
    projectId: 'tradex-ec203',
    authDomain: 'tradex-ec203.firebaseapp.com',
    storageBucket: 'tradex-ec203.firebasestorage.app',
    measurementId: 'G-YLMCV4N1QS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEoehEqsJ_8jKWLmw49SqN67zfVDJOY9o',
    appId: '1:321135360177:android:b634ef9f99686cd8064a90',
    messagingSenderId: '321135360177',
    projectId: 'tradex-ec203',
    storageBucket: 'tradex-ec203.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhBvd_xPsP-MleEoAFh69SE1bVWUXOFA',
    appId: '1:321135360177:ios:a4ce50878c21e91d064a90',
    messagingSenderId: '321135360177',
    projectId: 'tradex-ec203',
    storageBucket: 'tradex-ec203.firebasestorage.app',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClhBvd_xPsP-MleEoAFh69SE1bVWUXOFA',
    appId: '1:321135360177:ios:a4ce50878c21e91d064a90',
    messagingSenderId: '321135360177',
    projectId: 'tradex-ec203',
    storageBucket: 'tradex-ec203.firebasestorage.app',
    iosBundleId: 'com.example.redditTutorial',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA253aK1P1rhW9DhryYexhzs-oBpRIPMMw',
    appId: '1:321135360177:web:23f984aef7845597064a90',
    messagingSenderId: '321135360177',
    projectId: 'tradex-ec203',
    authDomain: 'tradex-ec203.firebaseapp.com',
    storageBucket: 'tradex-ec203.firebasestorage.app',
    measurementId: 'G-B2BCEQR6NZ',
  );

}